In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5,6,7,8,9,10,np.nan,11,120,234,543,333])
y=np.array([12,13,14,15,16,17,18,19,20,21,27,22,444,89,0,980])

### Leave-p-out Cross Validation (LpO CV)

In [3]:
from sklearn.model_selection import LeavePOut

In [4]:
lpo = LeavePOut(3)
lpo.get_n_splits(x)

560

In [5]:
for train_index, test_index in lpo.split(x):
    print("TRAIN:", train_index, "TEST:", test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [ 3  4  5  6  7  8  9 10 11 12 13 14 15] TEST: [0 1 2]
TRAIN: [ 2  4  5  6  7  8  9 10 11 12 13 14 15] TEST: [0 1 3]
TRAIN: [ 2  3  5  6  7  8  9 10 11 12 13 14 15] TEST: [0 1 4]
TRAIN: [ 2  3  4  6  7  8  9 10 11 12 13 14 15] TEST: [0 1 5]
TRAIN: [ 2  3  4  5  7  8  9 10 11 12 13 14 15] TEST: [0 1 6]
TRAIN: [ 2  3  4  5  6  8  9 10 11 12 13 14 15] TEST: [0 1 7]
TRAIN: [ 2  3  4  5  6  7  9 10 11 12 13 14 15] TEST: [0 1 8]
TRAIN: [ 2  3  4  5  6  7  8 10 11 12 13 14 15] TEST: [0 1 9]
TRAIN: [ 2  3  4  5  6  7  8  9 11 12 13 14 15] TEST: [ 0  1 10]
TRAIN: [ 2  3  4  5  6  7  8  9 10 12 13 14 15] TEST: [ 0  1 11]
TRAIN: [ 2  3  4  5  6  7  8  9 10 11 13 14 15] TEST: [ 0  1 12]
TRAIN: [ 2  3  4  5  6  7  8  9 10 11 12 14 15] TEST: [ 0  1 13]
TRAIN: [ 2  3  4  5  6  7  8  9 10 11 12 13 15] TEST: [ 0  1 14]
TRAIN: [ 2  3  4  5  6  7  8  9 10 11 12 13 14] TEST: [ 0  1 15]
TRAIN: [ 1  4  5  6  7  8  9 10 11 12 13 14 15] TEST: [0 2 3]
TRAIN: [ 1  3  5  6  7  8  9 10 11 12 13 14 15] TEST

### Leave-one-out Cross Validation (LOOCV) 

In [6]:
from sklearn.model_selection import LeaveOneOut

In [7]:
l = LeaveOneOut()

for train, test in l.split(x):

    print("%s %s"% (train,test))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [0]
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [1]
[ 0  1  3  4  5  6  7  8  9 10 11 12 13 14 15] [2]
[ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15] [3]
[ 0  1  2  3  5  6  7  8  9 10 11 12 13 14 15] [4]
[ 0  1  2  3  4  6  7  8  9 10 11 12 13 14 15] [5]
[ 0  1  2  3  4  5  7  8  9 10 11 12 13 14 15] [6]
[ 0  1  2  3  4  5  6  8  9 10 11 12 13 14 15] [7]
[ 0  1  2  3  4  5  6  7  9 10 11 12 13 14 15] [8]
[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15] [9]
[ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 15] [10]
[ 0  1  2  3  4  5  6  7  8  9 10 12 13 14 15] [11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 13 14 15] [12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 14 15] [13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15] [14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] [15]


In [8]:
loo = LeaveOneOut()
loo.get_n_splits(x)
for train_index, test_index in loo.split(x):
    print("TRAIN:", train_index, "TEST:", test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(x_train, x_test, y_train, y_test)

TRAIN: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] TEST: [0]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.  nan  11. 120. 234. 543.
 333.] [1.] [ 13  14  15  16  17  18  19  20  21  27  22 444  89   0 980] [12]
TRAIN: [ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15] TEST: [1]
[  1.   3.   4.   5.   6.   7.   8.   9.  10.  nan  11. 120. 234. 543.
 333.] [2.] [ 12  14  15  16  17  18  19  20  21  27  22 444  89   0 980] [13]
TRAIN: [ 0  1  3  4  5  6  7  8  9 10 11 12 13 14 15] TEST: [2]
[  1.   2.   4.   5.   6.   7.   8.   9.  10.  nan  11. 120. 234. 543.
 333.] [3.] [ 12  13  15  16  17  18  19  20  21  27  22 444  89   0 980] [14]
TRAIN: [ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15] TEST: [3]
[  1.   2.   3.   5.   6.   7.   8.   9.  10.  nan  11. 120. 234. 543.
 333.] [4.] [ 12  13  14  16  17  18  19  20  21  27  22 444  89   0 980] [15]
TRAIN: [ 0  1  2  3  5  6  7  8  9 10 11 12 13 14 15] TEST: [4]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.  nan  11. 120. 234. 543.
 333.] [5

## Non-Exhaustive Cross validation 

### K-fold Cross Validation 

In [9]:
from sklearn.model_selection import KFold

In [10]:
kf = KFold(n_splits=3, shuffle=True, random_state=None)

for train, test in kf.split(x):

    print("Train data",train,"Test data",test)

Train data [ 1  3  4  6  7  9 10 11 13 14] Test data [ 0  2  5  8 12 15]
Train data [ 0  2  3  4  5  6  7  8  9 12 15] Test data [ 1 10 11 13 14]
Train data [ 0  1  2  5  8 10 11 12 13 14 15] Test data [3 4 6 7 9]


In [11]:
kf = KFold(n_splits=2)
kf.get_n_splits(x)

print(kf)

KFold(n_splits=2, random_state=None, shuffle=False)


In [12]:
for train_index, test_index in kf.split(x):
    print("TRAIN:", train_index, "TEST:", test_index)
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [ 8  9 10 11 12 13 14 15] TEST: [0 1 2 3 4 5 6 7]
TRAIN: [0 1 2 3 4 5 6 7] TEST: [ 8  9 10 11 12 13 14 15]


### Stratified K-fold Cross Validation 

In [13]:
from sklearn.model_selection import StratifiedKFold

In [14]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
Y = np.array([0, 0, 1, 1])

In [15]:
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(x, y)
print(skf)

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)


In [16]:
for train_index, test_index in skf.split(X, Y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]

TRAIN: [1 3] TEST: [0 2]
TRAIN: [0 2] TEST: [1 3]


### Holdout Method 

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [19]:
print("X_train: ",x_train)
print("X_test: ",x_test)
print("y_train: ",y_train)
print("y_test: ",y_test)

X_train:  [  9.  10.   3. 333.   5.   8.  nan 120.   4.   7.]
X_test:  [  1.   2.   6. 543. 234.  11.]
y_train:  [ 20  21  14 980  16  19  27 444  15  18]
y_test:  [12 13 17  0 89 22]


### Monte Carlo Cross Validation 

In [20]:
from sklearn.model_selection import train_test_split
from sklearn import svm

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.4, random_state=0)
print(x_train)
print(y_train)
print(X_test)
print(y_test)

[543.  nan   8. 333.  11.   4.   1.   6. 120.]
[  0  27  19 980  22  15  12  17 444]
[[3 4]
 [3 4]]
[13 18 20 21 89 16 14]
